### ISSUE TITLE
[Feat] 채팅 로직 구현하기

### ISSUE THREAD

**Issue by srkimdev** [BuddyBuddy-iOS/BuddyBuddy#21]
# 📝To do
- [x] 채팅 DB 구현
- [x] 마지막으로 읽은 메세지를 기준으로 새로운 메세지에 대한 DB 저장 및 테이블뷰 갱신 로직 구현
- [x] socketIO 라이브러리를 이용해서 소켓 통신

**Comment by isakatty** [comment]
@srkimdev 성률님! 어제 결정했던 DIContainer의 형태를 정리해보면,

1. DIContainer에서 Repository만 등록 ~~재사용이 되는 UseCase의 경우에는 UseCase까지 등록.~~(11.19 수정)
2. Network는 DIContainer 등록 X
3. 기존 네트워크 프로토콜의 extension에 구현된 accessTokenRefresh 메서드의 기능을 interceptor 내부에서 직접 통신하는 형태로 변경.
4. 그에 따라 Network 통신 request시 Interceptor를 객체 생성해서 주입
5. NetworkService를 DIContainer에 등록하지 않기 때문에, Repository에서는 network를 주입받는 형태로 변경.
6. dmUseCase가 앞으로 어떻게 변경될지 모르지만 현 상태에서는 1의 이유로 DIContainer에 등록하지 않고, 해당 객체 내부에서 Repository를 프로퍼티 래퍼를 활용해 꺼내 사용

입니다. 
(홈VC에 임시 로그인이 들어온 부분도 네트워크를 등록하지 않아서 사용하지 못할 텐데, 임시로 AuthRepository를 만들어 등록시켜서 사용하는 형태로 변경되어야 할 것 같아요. 이후 제가 작업하게 될 영역이라 이거 관련해서는 같이 이야기해 보면 좋을 것 같아요!)

작성된 내용 중에 설명이 부족한 부분이 있거나 모호한 부분이 있으면 말씀해주세요 !
